import datetime
import json
import os
import google.generativeai as genai

# ==============================
# CONFIGURATION
# ==============================
GEMINI_API_KEY = "AIzaSyBPO7BGFtM_Xlv8OIpGxNd5jd-BqhoXjnU"  # Get from https://aistudio.google.com/
genai.configure(api_key=GEMINI_API_KEY)
LOG_FILE = "chat_log.json"

chat_history = []
# ==============================
# MASSIVE STATIC FAQ DATA
# ==============================
faq_data = {
    # --- Greetings ---
    "hod of mca": "👨‍🎓 The Head of the Department (MCA) is **Dr. R. AROUL CANESSANE, M.E., Ph.D.**",
       "faculty of mca": (
        "👩‍🏫 Faculty of MCA Department:\n"
        "• Dr. J. Palanimeera\n"
        "• Dr. R. Tamilselvi. P\n"
        "• Ms. Roshini. M\n"
        "• Dr. R. Rajeswari"),
    "roshini": "Ms. Roshini, Faculty of MCA, handles subjects very well and is appreciated by students.",
    "tamilselvi": "Dr. R. Tamilselvi, Faculty of MCA, explains complex topics in a simple and clear way.",
    "rajeswari": "Dr. R. Rajeswari, Faculty of MCA, is supportive and encourages research-oriented learning.",
    "palanimeera": "Dr. J. Palanimeera, Faculty of MCA, teaches with excellent clarity and knowledge.",
    "library_0": "You can access e-resources using your student login.",
    "who stole the 30 mouse": "🖱️ The lab assistant *Juliet* stole the 30 mouse! 😂",
    "mouse stolen": "🖱️ The lab assistant *Juliet* took them away!",
    "juliet": "⚡ Juliet is the lab assistant who (allegedly) stole the 30 mouse 🖱️.",
    "greeting_1": "Hello! How can I help you today?",
    "placement_2": "We have a placement record of over 90%.",
    "greeting_3": "Hi there! What can I do for you?",
    "hostel_4": "Hostel fees depend on the type of accommodation.",
    "placement_5": "We have a placement record of over 90%.",
    "admission_6": "Admission details are available on our website.",
    "courses_7": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_8": "You can apply online at sathyabama.ac.in/admissions.",
    "hostel_9": "Hostel fees depend on the type of accommodation.",
    "courses_10": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "greeting_11": "Hello! How can I help you today?",
    "events_12": "Hackathons and workshops are conducted regularly.",
    "placement_13": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "fees_14": "M.Tech fees: ₹1,80,000 per year.",
    "events_15": "Hackathons and workshops are conducted regularly.",
    "placement_16": "We have a placement record of over 90%.",
    "placement_17": "We have a placement record of over 90%.",
    "greeting_18": "Hello! How can I help you today?",
    "hostel_19": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_20": "We host cultural and technical events throughout the year.",
    "courses_21": "Our courses include engineering, management, science, and humanities.",
    "fees_22": "PhD fees vary depending on the department.",
    "admission_23": "For admissions, visit our official portal.",
    "hostel_24": "Separate hostels for boys and girls are available.",
    "placement_25": "We have a placement record of over 90%.",
    "hostel_26": "Separate hostels for boys and girls are available.",
    "courses_27": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_28": "Sathyabama Fest is our annual cultural festival.",
    "placement_29": "Our highest package last year was ₹45 LPA.",
    "hostel_30": "Hostel fees depend on the type of accommodation.",
    "library_31": "You can access e-resources using your student login.",
    "courses_32": "Our courses include engineering, management, science, and humanities.",
    "library_33": "Library is open from 8 AM to 8 PM.",
    "admission_34": "Admission details are available on our website.",
    "library_35": "Library is open from 8 AM to 8 PM.",
    "admission_36": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_37": "We have a placement record of over 90%.",
    "library_38": "Library is open from 8 AM to 8 PM.",
    "greeting_39": "Greetings! How may I assist you?",
    "greeting_40": "Hi there! What can I do for you?",
    "greeting_41": "Hi there! What can I do for you?",
    "events_42": "Sathyabama Fest is our annual cultural festival.",
    "placement_43": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "hostel_44": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "admission_45": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_46": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "courses_47": "Visit sathyabama.ac.in/courses for the complete list.",
    "courses_48": "Our courses include engineering, management, science, and humanities.",
    "hostel_49": "Hostel fees depend on the type of accommodation.",
    "hostel_50": "Hostel fees depend on the type of accommodation.",
    "hostel_51": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_52": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_53": "You can access e-resources using your student login.",
    "hostel_54": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_55": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "greeting_56": "Hi there! What can I do for you?",
    "courses_57": "Our courses include engineering, management, science, and humanities.",
    "admission_58": "For admissions, visit our official portal.",
    "events_59": "We host cultural and technical events throughout the year.",
    "greeting_60": "Hi there! What can I do for you?",
    "hostel_61": "Separate hostels for boys and girls are available.",
    "hostel_62": "Hostel fees depend on the type of accommodation.",
    "events_63": "Sathyabama Fest is our annual cultural festival.",
    "admission_64": "For admissions, visit our official portal.",
    "fees_65": "M.Tech fees: ₹1,80,000 per year.",
    "fees_66": "B.Tech fees: ₹2,00,000 per year.",
    "hostel_67": "Hostel fees depend on the type of accommodation.",
    "admission_68": "For admissions, visit our official portal.",
    "placement_69": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "greeting_70": "Greetings! How may I assist you?",
    "fees_71": "MBA fees: ₹2,50,000 per year.",
    "events_72": "Hackathons and workshops are conducted regularly.",
    "courses_73": "Visit sathyabama.ac.in/courses for the complete list.",
    "events_74": "We host cultural and technical events throughout the year.",
    "events_75": "We host cultural and technical events throughout the year.",
    "admission_76": "Admission details are available on our website.",
    "admission_77": "Admission details are available on our website.",
    "courses_78": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_79": "Separate hostels for boys and girls are available.",
    "courses_80": "Visit sathyabama.ac.in/courses for the complete list.",
    "greeting_81": "Greetings! How may I assist you?",
    "fees_82": "M.Tech fees: ₹1,80,000 per year.",
    "events_83": "We host cultural and technical events throughout the year.",
    "admission_84": "Admission details are available on our website.",
    "admission_85": "You can apply online at sathyabama.ac.in/admissions.",
    "hostel_86": "Hostel fees depend on the type of accommodation.",
    "events_87": "Hackathons and workshops are conducted regularly.",
    "placement_88": "We have a placement record of over 90%.",
    "library_89": "Library is open from 8 AM to 8 PM.",
    "fees_90": "M.Tech fees: ₹1,80,000 per year.",
    "admission_91": "Admission details are available on our website.",
    "fees_92": "B.Tech fees: ₹2,00,000 per year.",
    "library_93": "Library is open from 8 AM to 8 PM.",
    "placement_94": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "events_95": "We host cultural and technical events throughout the year.",
    "admission_96": "For admissions, visit our official portal.",
    "fees_97": "B.Tech fees: ₹2,00,000 per year.",
    "greeting_98": "Hi there! What can I do for you?",
    "greeting_99": "Greetings! How may I assist you?",
    "hostel_100": "Separate hostels for boys and girls are available.",
    "events_101": "Hackathons and workshops are conducted regularly.",
    "events_102": "Sathyabama Fest is our annual cultural festival.",
    "events_103": "Sathyabama Fest is our annual cultural festival.",
    "admission_104": "Admission details are available on our website.",
    "hostel_105": "Hostel fees depend on the type of accommodation.",
    "placement_106": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "placement_107": "We have a placement record of over 90%.",
    "fees_108": "M.Tech fees: ₹1,80,000 per year.",
    "library_109": "Books can be borrowed for a period of 15 days.",
    "greeting_110": "Hi there! What can I do for you?",
    "courses_111": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_112": "PhD fees vary depending on the department.",
    "events_113": "We host cultural and technical events throughout the year.",
    "placement_114": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "hostel_115": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_116": "Visit sathyabama.ac.in/courses for the complete list.",
    "courses_117": "Visit sathyabama.ac.in/courses for the complete list.",
    "courses_118": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_119": "We have a placement record of over 90%.",
    "hostel_120": "Separate hostels for boys and girls are available.",
    "hostel_121": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_122": "Separate hostels for boys and girls are available.",
    "events_123": "Sathyabama Fest is our annual cultural festival.",
    "placement_124": "We have a placement record of over 90%.",
    "fees_125": "M.Tech fees: ₹1,80,000 per year.",
    "courses_126": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_127": "Sathyabama Fest is our annual cultural festival.",
    "placement_128": "We have a placement record of over 90%.",
    "courses_129": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_130": "B.Tech fees: ₹2,00,000 per year.",
    "hostel_131": "Separate hostels for boys and girls are available.",
    "hostel_132": "Hostel fees depend on the type of accommodation.",
    "courses_133": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_134": "Books can be borrowed for a period of 15 days.",
    "hostel_135": "Separate hostels for boys and girls are available.",
    "courses_136": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_137": "Separate hostels for boys and girls are available.",
    "fees_138": "B.Tech fees: ₹2,00,000 per year.",
    "fees_139": "B.Tech fees: ₹2,00,000 per year.",
    "admission_140": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_141": "Our highest package last year was ₹45 LPA.",
    "placement_142": "We have a placement record of over 90%.",
    "events_143": "Hackathons and workshops are conducted regularly.",
    "fees_144": "MBA fees: ₹2,50,000 per year.",
    "fees_145": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_146": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_147": "We host cultural and technical events throughout the year.",
    "courses_148": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_149": "We host cultural and technical events throughout the year.",
    "library_150": "Books can be borrowed for a period of 15 days.",
    "placement_151": "Our highest package last year was ₹45 LPA.",
    "library_152": "Books can be borrowed for a period of 15 days.",
    "greeting_153": "Hello! How can I help you today?",
    "fees_154": "B.Tech fees: ₹2,00,000 per year.",
    "fees_155": "M.Tech fees: ₹1,80,000 per year.",
    "placement_156": "Our highest package last year was ₹45 LPA.",
    "events_157": "Sathyabama Fest is our annual cultural festival.",
    "admission_158": "You can apply online at sathyabama.ac.in/admissions.",
    "greeting_159": "Hello! How can I help you today?",
    "greeting_160": "Hi there! What can I do for you?",
    "admission_161": "For admissions, visit our official portal.",
    "library_162": "Books can be borrowed for a period of 15 days.",
    "courses_163": "Visit sathyabama.ac.in/courses for the complete list.",
    "admission_164": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_165": "PhD fees vary depending on the department.",
    "greeting_166": "Greetings! How may I assist you?",
    "courses_167": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_168": "Separate hostels for boys and girls are available.",
    "fees_169": "MBA fees: ₹2,50,000 per year.",
    "fees_170": "B.Tech fees: ₹2,00,000 per year.",
    "placement_171": "Our highest package last year was ₹45 LPA.",
    "courses_172": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_173": "MBA fees: ₹2,50,000 per year.",
    "fees_174": "MBA fees: ₹2,50,000 per year.",
    "library_175": "Library is open from 8 AM to 8 PM.",
    "placement_176": "We have a placement record of over 90%.",
    "placement_177": "We have a placement record of over 90%.",
    "library_178": "Books can be borrowed for a period of 15 days.",
    "placement_179": "We have a placement record of over 90%.",
    "library_180": "Library is open from 8 AM to 8 PM.",
    "library_181": "Library is open from 8 AM to 8 PM.",
    "events_182": "Hackathons and workshops are conducted regularly.",
    "fees_183": "PhD fees vary depending on the department.",
    "fees_184": "PhD fees vary depending on the department.",
    "admission_185": "Admission details are available on our website.",
    "library_186": "Library is open from 8 AM to 8 PM.",
    "greeting_187": "Hi there! What can I do for you?",
    "events_188": "Hackathons and workshops are conducted regularly.",
    "admission_189": "For admissions, visit our official portal.",
    "admission_190": "Admission details are available on our website.",
    "courses_191": "Our courses include engineering, management, science, and humanities.",
    "greeting_192": "Hello! How can I help you today?",
    "greeting_193": "Hello! How can I help you today?",
    "library_194": "Library is open from 8 AM to 8 PM.",
    "library_195": "Books can be borrowed for a period of 15 days.",
    "events_196": "Hackathons and workshops are conducted regularly.",
    "events_197": "We host cultural and technical events throughout the year.",
    "fees_198": "PhD fees vary depending on the department.",
    "greeting_199": "Hi there! What can I do for you?",
    "greeting_200": "Greetings! How may I assist you?",
    "hostel_201": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_202": "MBA fees: ₹2,50,000 per year.",
    "courses_203": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_204": "MBA fees: ₹2,50,000 per year.",
    "greeting_205": "Hi there! What can I do for you?",
    "courses_206": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_207": "Admission details are available on our website.",
    "placement_208": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "greeting_209": "Hi there! What can I do for you?",
    "greeting_210": "Hello! How can I help you today?",
    "library_211": "Books can be borrowed for a period of 15 days.",
    "admission_212": "You can apply online at sathyabama.ac.in/admissions.",
    "greeting_213": "Hi there! What can I do for you?",
    "hostel_214": "Separate hostels for boys and girls are available.",
    "admission_215": "Admission details are available on our website.",
    "library_216": "Books can be borrowed for a period of 15 days.",
    "admission_217": "Admission details are available on our website.",
    "events_218": "Sathyabama Fest is our annual cultural festival.",
    "hostel_219": "Hostel fees depend on the type of accommodation.",
    "courses_220": "Our courses include engineering, management, science, and humanities.",
    "admission_221": "Admission details are available on our website.",
    "events_222": "We host cultural and technical events throughout the year.",
    "courses_223": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_224": "PhD fees vary depending on the department.",
    "events_225": "We host cultural and technical events throughout the year.",
    "courses_226": "Our courses include engineering, management, science, and humanities.",
    "library_227": "You can access e-resources using your student login.",
    "admission_228": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_229": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_230": "Library is open from 8 AM to 8 PM.",
    "placement_231": "We have a placement record of over 90%.",
    "courses_232": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_233": "Admission details are available on our website.",
    "placement_234": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "greeting_235": "Greetings! How may I assist you?",
    "library_236": "Library is open from 8 AM to 8 PM.",
    "fees_237": "M.Tech fees: ₹1,80,000 per year.",
    "placement_238": "We have a placement record of over 90%.",
    "events_239": "Hackathons and workshops are conducted regularly.",
    "hostel_240": "Separate hostels for boys and girls are available.",
    "courses_241": "Visit sathyabama.ac.in/courses for the complete list.",
    "admission_242": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_243": "B.Tech fees: ₹2,00,000 per year.",
    "library_244": "You can access e-resources using your student login.",
    "library_245": "Library is open from 8 AM to 8 PM.",
    "fees_246": "MBA fees: ₹2,50,000 per year.",
    "placement_247": "We have a placement record of over 90%.",
    "greeting_248": "Hello! How can I help you today?",
    "events_249": "We host cultural and technical events throughout the year.",
    "library_250": "Library is open from 8 AM to 8 PM.",
    "events_251": "Sathyabama Fest is our annual cultural festival.",
    "hostel_252": "Hostel fees depend on the type of accommodation.",
    "fees_253": "MBA fees: ₹2,50,000 per year.",
    "events_254": "Sathyabama Fest is our annual cultural festival.",
    "hostel_255": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "greeting_256": "Greetings! How may I assist you?",
    "library_257": "You can access e-resources using your student login.",
    "fees_258": "MBA fees: ₹2,50,000 per year.",
    "library_259": "Library is open from 8 AM to 8 PM.",
    "greeting_260": "Greetings! How may I assist you?",
    "library_261": "Library is open from 8 AM to 8 PM.",
    "events_262": "Hackathons and workshops are conducted regularly.",
    "placement_263": "Our highest package last year was ₹45 LPA.",
    "library_264": "You can access e-resources using your student login.",
    "hostel_265": "Separate hostels for boys and girls are available.",
    "greeting_266": "Greetings! How may I assist you?",
    "hostel_267": "Hostel fees depend on the type of accommodation.",
    "placement_268": "We have a placement record of over 90%.",
    "hostel_269": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_270": "Our courses include engineering, management, science, and humanities.",
    "fees_271": "PhD fees vary depending on the department.",
    "hostel_272": "Hostel fees depend on the type of accommodation.",
    "library_273": "Books can be borrowed for a period of 15 days.",
    "greeting_274": "Greetings! How may I assist you?",
    "library_275": "Library is open from 8 AM to 8 PM.",
    "courses_276": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_277": "Books can be borrowed for a period of 15 days.",
    "fees_278": "MBA fees: ₹2,50,000 per year.",
    "fees_279": "MBA fees: ₹2,50,000 per year.",
    "admission_280": "You can apply online at sathyabama.ac.in/admissions.",
    "admission_281": "For admissions, visit our official portal.",
    "fees_282": "M.Tech fees: ₹1,80,000 per year.",
    "admission_283": "For admissions, visit our official portal.",
    "events_284": "Hackathons and workshops are conducted regularly.",
    "courses_285": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "greeting_286": "Greetings! How may I assist you?",
    "library_287": "You can access e-resources using your student login.",
    "admission_288": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_289": "Our highest package last year was ₹45 LPA.",
    "admission_290": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_291": "Visit sathyabama.ac.in/courses for the complete list.",
    "placement_292": "We have a placement record of over 90%.",
    "admission_293": "Admission details are available on our website.",
    "hostel_294": "Separate hostels for boys and girls are available.",
    "admission_295": "For admissions, visit our official portal.",
    "courses_296": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_297": "M.Tech fees: ₹1,80,000 per year.",
    "fees_298": "M.Tech fees: ₹1,80,000 per year.",
    "courses_299": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_300": "Library is open from 8 AM to 8 PM.",
    "library_301": "Library is open from 8 AM to 8 PM.",
    "courses_302": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_303": "Separate hostels for boys and girls are available.",
    "hostel_304": "Separate hostels for boys and girls are available.",
    "courses_305": "Visit sathyabama.ac.in/courses for the complete list.",
    "events_306": "Hackathons and workshops are conducted regularly.",
    "hostel_307": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_308": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "placement_309": "We have a placement record of over 90%.",
    "courses_310": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_311": "M.Tech fees: ₹1,80,000 per year.",
    "admission_312": "For admissions, visit our official portal.",
    "admission_313": "Admission details are available on our website.",
    "courses_314": "Visit sathyabama.ac.in/courses for the complete list.",
    "placement_315": "We have a placement record of over 90%.",
    "library_316": "Library is open from 8 AM to 8 PM.",
    "greeting_317": "Greetings! How may I assist you?",
    "greeting_318": "Hello! How can I help you today?",
    "events_319": "Hackathons and workshops are conducted regularly.",
    "admission_320": "For admissions, visit our official portal.",
    "admission_321": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_322": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "admission_323": "For admissions, visit our official portal.",
    "events_324": "Hackathons and workshops are conducted regularly.",
    "admission_325": "For admissions, visit our official portal.",
    "events_326": "Sathyabama Fest is our annual cultural festival.",
    "greeting_327": "Hello! How can I help you today?",
    "hostel_328": "Hostel fees depend on the type of accommodation.",
    "fees_329": "PhD fees vary depending on the department.",
    "courses_330": "Our courses include engineering, management, science, and humanities.",
    "placement_331": "We have a placement record of over 90%.",
    "library_332": "You can access e-resources using your student login.",
    "hostel_333": "Separate hostels for boys and girls are available.",
    "courses_334": "Our courses include engineering, management, science, and humanities.",
    "events_335": "Sathyabama Fest is our annual cultural festival.",
    "courses_336": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_337": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_338": "MBA fees: ₹2,50,000 per year.",
    "fees_339": "PhD fees vary depending on the department.",
    "hostel_340": "Hostel fees depend on the type of accommodation.",
    "placement_341": "We have a placement record of over 90%.",
    "hostel_342": "Hostel fees depend on the type of accommodation.",
    "courses_343": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_344": "Books can be borrowed for a period of 15 days.",
    "admission_345": "For admissions, visit our official portal.",
    "admission_346": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_347": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_348": "Books can be borrowed for a period of 15 days.",
    "fees_349": "B.Tech fees: ₹2,00,000 per year.",
    "fees_350": "PhD fees vary depending on the department.",
    "admission_351": "For admissions, visit our official portal.",
    "library_352": "Books can be borrowed for a period of 15 days.",
    "courses_353": "Our courses include engineering, management, science, and humanities.",
    "hostel_354": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_355": "We have a placement record of over 90%.",
    "placement_356": "Our highest package last year was ₹45 LPA.",
    "courses_357": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_358": "Books can be borrowed for a period of 15 days.",
    "admission_359": "For admissions, visit our official portal.",
    "events_360": "Hackathons and workshops are conducted regularly.",
    "fees_361": "M.Tech fees: ₹1,80,000 per year.",
    "library_362": "Books can be borrowed for a period of 15 days.",
    "placement_363": "We have a placement record of over 90%.",
    "courses_364": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_365": "Library is open from 8 AM to 8 PM.",
    "hostel_366": "Separate hostels for boys and girls are available.",
    "placement_367": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_368": "You can access e-resources using your student login.",
    "hostel_369": "Separate hostels for boys and girls are available.",
    "placement_370": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "fees_371": "MBA fees: ₹2,50,000 per year.",
    "library_372": "You can access e-resources using your student login.",
    "admission_373": "For admissions, visit our official portal.",
    "hostel_374": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_375": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "fees_376": "B.Tech fees: ₹2,00,000 per year.",
    "admission_377": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_378": "Visit sathyabama.ac.in/courses for the complete list.",
    "admission_379": "You can apply online at sathyabama.ac.in/admissions.",
    "library_380": "Library is open from 8 AM to 8 PM.",
    "courses_381": "Our courses include engineering, management, science, and humanities.",
    "admission_382": "You can apply online at sathyabama.ac.in/admissions.",
    "events_383": "We host cultural and technical events throughout the year.",
    "placement_384": "We have a placement record of over 90%.",
    "library_385": "Library is open from 8 AM to 8 PM.",
    "courses_386": "Our courses include engineering, management, science, and humanities.",
    "courses_387": "Our courses include engineering, management, science, and humanities.",
    "greeting_388": "Hello! How can I help you today?",
    "greeting_389": "Greetings! How may I assist you?",
    "events_390": "Sathyabama Fest is our annual cultural festival.",
    "hostel_391": "Hostel fees depend on the type of accommodation.",
    "library_392": "Library is open from 8 AM to 8 PM.",
    "library_393": "Books can be borrowed for a period of 15 days.",
    "hostel_394": "Hostel fees depend on the type of accommodation.",
    "fees_395": "M.Tech fees: ₹1,80,000 per year.",
    "library_396": "Books can be borrowed for a period of 15 days.",
    "courses_397": "Visit sathyabama.ac.in/courses for the complete list.",
    "admission_398": "You can apply online at sathyabama.ac.in/admissions.",
    "hostel_399": "Separate hostels for boys and girls are available.",
    "library_400": "You can access e-resources using your student login.",
    "greeting_401": "Hi there! What can I do for you?",
    "fees_402": "MBA fees: ₹2,50,000 per year.",
    "admission_403": "Admission details are available on our website.",
    "greeting_404": "Greetings! How may I assist you?",
    "courses_405": "Visit sathyabama.ac.in/courses for the complete list.",
    "events_406": "Sathyabama Fest is our annual cultural festival.",
    "admission_407": "For admissions, visit our official portal.",
    "courses_408": "Our courses include engineering, management, science, and humanities.",
    "hostel_409": "Separate hostels for boys and girls are available.",
    "courses_410": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "greeting_411": "Greetings! How may I assist you?",
    "library_412": "Library is open from 8 AM to 8 PM.",
    "hostel_413": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_414": "B.Tech fees: ₹2,00,000 per year.",
    "hostel_415": "Hostel fees depend on the type of accommodation.",
    "admission_416": "Admission details are available on our website.",
    "fees_417": "PhD fees vary depending on the department.",
    "fees_418": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_419": "Hostel fees depend on the type of accommodation.",
    "admission_420": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_421": "PhD fees vary depending on the department.",
    "placement_422": "We have a placement record of over 90%.",
    "events_423": "Hackathons and workshops are conducted regularly.",
    "hostel_424": "Separate hostels for boys and girls are available.",
    "courses_425": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "hostel_426": "Hostel fees depend on the type of accommodation.",
    "greeting_427": "Greetings! How may I assist you?",
    "events_428": "Hackathons and workshops are conducted regularly.",
    "events_429": "Hackathons and workshops are conducted regularly.",
    "events_430": "Sathyabama Fest is our annual cultural festival.",
    "courses_431": "Our courses include engineering, management, science, and humanities.",
    "admission_432": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_433": "B.Tech fees: ₹2,00,000 per year.",
    "admission_434": "For admissions, visit our official portal.",
    "hostel_435": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "greeting_436": "Hi there! What can I do for you?",
    "hostel_437": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_438": "Sathyabama Fest is our annual cultural festival.",
    "placement_439": "We have a placement record of over 90%.",
    "admission_440": "For admissions, visit our official portal.",
    "hostel_441": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_442": "Our courses include engineering, management, science, and humanities.",
    "admission_443": "You can apply online at sathyabama.ac.in/admissions.",
    "events_444": "Hackathons and workshops are conducted regularly.",
    "courses_445": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_446": "MBA fees: ₹2,50,000 per year.",
    "library_447": "Books can be borrowed for a period of 15 days.",
    "hostel_448": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "greeting_449": "Hi there! What can I do for you?",
    "courses_450": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_451": "We have a placement record of over 90%.",
    "greeting_452": "Greetings! How may I assist you?",
    "hostel_453": "Separate hostels for boys and girls are available.",
    "admission_454": "For admissions, visit our official portal.",
    "placement_455": "We have a placement record of over 90%.",
    "fees_456": "MBA fees: ₹2,50,000 per year.",
    "fees_457": "PhD fees vary depending on the department.",
    "events_458": "Hackathons and workshops are conducted regularly.",
    "library_459": "Books can be borrowed for a period of 15 days.",
    "fees_460": "B.Tech fees: ₹2,00,000 per year.",
    "courses_461": "Our courses include engineering, management, science, and humanities.",
    "library_462": "You can access e-resources using your student login.",
    "events_463": "We host cultural and technical events throughout the year.",
    "courses_464": "Our courses include engineering, management, science, and humanities.",
    "placement_465": "We have a placement record of over 90%.",
    "events_466": "Hackathons and workshops are conducted regularly.",
    "greeting_467": "Hello! How can I help you today?",
    "hostel_468": "Hostel fees depend on the type of accommodation.",
    "library_469": "Books can be borrowed for a period of 15 days.",
    "courses_470": "Our courses include engineering, management, science, and humanities.",
    "hostel_471": "Hostel fees depend on the type of accommodation.",
    "library_472": "You can access e-resources using your student login.",
    "hostel_473": "Hostel fees depend on the type of accommodation.",
    "hostel_474": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "library_475": "You can access e-resources using your student login.",
    "placement_476": "Our highest package last year was ₹45 LPA.",
    "fees_477": "B.Tech fees: ₹2,00,000 per year.",
    "hostel_478": "Separate hostels for boys and girls are available.",
    "events_479": "Sathyabama Fest is our annual cultural festival.",
    "admission_480": "For admissions, visit our official portal.",
    "library_481": "Books can be borrowed for a period of 15 days.",
    "hostel_482": "Separate hostels for boys and girls are available.",
    "courses_483": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_484": "Books can be borrowed for a period of 15 days.",
    "admission_485": "Admission details are available on our website.",
    "events_486": "We host cultural and technical events throughout the year.",
    "events_487": "We host cultural and technical events throughout the year.",
    "greeting_488": "Hello! How can I help you today?",
    "admission_489": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_490": "B.Tech fees: ₹2,00,000 per year.",
    "placement_491": "We have a placement record of over 90%.",
    "admission_492": "For admissions, visit our official portal.",
    "library_493": "Library is open from 8 AM to 8 PM.",
    "admission_494": "You can apply online at sathyabama.ac.in/admissions.",
    "library_495": "Library is open from 8 AM to 8 PM.",
    "library_496": "Library is open from 8 AM to 8 PM.",
    "greeting_497": "Greetings! How may I assist you?",
    "hostel_498": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "admission_499": "For admissions, visit our official portal.",
    "hostel_500": "Separate hostels for boys and girls are available.",
    "admission_501": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_502": "PhD fees vary depending on the department.",
    "library_503": "Books can be borrowed for a period of 15 days.",
    "events_504": "Hackathons and workshops are conducted regularly.",
    "hostel_505": "Separate hostels for boys and girls are available.",
    "greeting_506": "Hello! How can I help you today?",
    "fees_507": "MBA fees: ₹2,50,000 per year.",
    "courses_508": "Our courses include engineering, management, science, and humanities.",
    "courses_509": "Our courses include engineering, management, science, and humanities.",
    "events_510": "Hackathons and workshops are conducted regularly.",
    "events_511": "Hackathons and workshops are conducted regularly.",
    "courses_512": "Our courses include engineering, management, science, and humanities.",
    "greeting_513": "Hello! How can I help you today?",
    "placement_514": "We have a placement record of over 90%.",
    "placement_515": "Our highest package last year was ₹45 LPA.",
    "admission_516": "Admission details are available on our website.",
    "greeting_517": "Hello! How can I help you today?",
    "admission_518": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_519": "We have a placement record of over 90%.",
    "courses_520": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_521": "Library is open from 8 AM to 8 PM.",
    "courses_522": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_523": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_524": "Our courses include engineering, management, science, and humanities.",
    "library_525": "You can access e-resources using your student login.",
    "events_526": "Sathyabama Fest is our annual cultural festival.",
    "placement_527": "Our highest package last year was ₹45 LPA.",
    "events_528": "Hackathons and workshops are conducted regularly.",
    "hostel_529": "Hostel fees depend on the type of accommodation.",
    "events_530": "Hackathons and workshops are conducted regularly.",
    "greeting_531": "Hi there! What can I do for you?",
    "greeting_532": "Hi there! What can I do for you?",
    "courses_533": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_534": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_535": "B.Tech fees: ₹2,00,000 per year.",
    "courses_536": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_537": "B.Tech fees: ₹2,00,000 per year.",
    "greeting_538": "Hello! How can I help you today?",
    "admission_539": "Admission details are available on our website.",
    "greeting_540": "Greetings! How may I assist you?",
    "hostel_541": "Hostel fees depend on the type of accommodation.",
    "placement_542": "We have a placement record of over 90%.",
    "fees_543": "PhD fees vary depending on the department.",
    "fees_544": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_545": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_546": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_547": "Sathyabama Fest is our annual cultural festival.",
    "fees_548": "MBA fees: ₹2,50,000 per year.",
    "hostel_549": "Separate hostels for boys and girls are available.",
    "fees_550": "MBA fees: ₹2,50,000 per year.",
    "library_551": "You can access e-resources using your student login.",
    "library_552": "Library is open from 8 AM to 8 PM.",
    "fees_553": "MBA fees: ₹2,50,000 per year.",
    "courses_554": "Our courses include engineering, management, science, and humanities.",
    "events_555": "Sathyabama Fest is our annual cultural festival.",
    "events_556": "We host cultural and technical events throughout the year.",
    "events_557": "Hackathons and workshops are conducted regularly.",
    "greeting_558": "Hi there! What can I do for you?",
    "courses_559": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_560": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "courses_561": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_562": "MBA fees: ₹2,50,000 per year.",
    "admission_563": "You can apply online at sathyabama.ac.in/admissions.",
    "events_564": "Sathyabama Fest is our annual cultural festival.",
    "hostel_565": "Separate hostels for boys and girls are available.",
    "greeting_566": "Hi there! What can I do for you?",
    "fees_567": "M.Tech fees: ₹1,80,000 per year.",
    "library_568": "Library is open from 8 AM to 8 PM.",
    "placement_569": "Our highest package last year was ₹45 LPA.",
    "hostel_570": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_571": "Sathyabama Fest is our annual cultural festival.",
    "placement_572": "We have a placement record of over 90%.",
    "placement_573": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "courses_574": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_575": "MBA fees: ₹2,50,000 per year.",
    "admission_576": "For admissions, visit our official portal.",
    "hostel_577": "Hostel fees depend on the type of accommodation.",
    "fees_578": "PhD fees vary depending on the department.",
    "placement_579": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "events_580": "We host cultural and technical events throughout the year.",
    "courses_581": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_582": "Sathyabama Fest is our annual cultural festival.",
    "library_583": "Library is open from 8 AM to 8 PM.",
    "hostel_584": "Hostel fees depend on the type of accommodation.",
    "library_585": "Books can be borrowed for a period of 15 days.",
    "events_586": "Hackathons and workshops are conducted regularly.",
    "hostel_587": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_588": "B.Tech fees: ₹2,00,000 per year.",
    "events_589": "We host cultural and technical events throughout the year.",
    "courses_590": "Our courses include engineering, management, science, and humanities.",
    "hostel_591": "Hostel fees depend on the type of accommodation.",
    "fees_592": "MBA fees: ₹2,50,000 per year.",
    "greeting_593": "Hello! How can I help you today?",
    "greeting_594": "Hello! How can I help you today?",
    "placement_595": "We have a placement record of over 90%.",
    "events_596": "We host cultural and technical events throughout the year.",
    "admission_597": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_598": "Our courses include engineering, management, science, and humanities.",
    "events_599": "Hackathons and workshops are conducted regularly.",
    "placement_600": "We have a placement record of over 90%.",
    "admission_601": "For admissions, visit our official portal.",
    "admission_602": "For admissions, visit our official portal.",
    "hostel_603": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_604": "Hostel fees depend on the type of accommodation.",
    "fees_605": "MBA fees: ₹2,50,000 per year.",
    "courses_606": "Visit sathyabama.ac.in/courses for the complete list.",
    "admission_607": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_608": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_609": "PhD fees vary depending on the department.",
    "library_610": "Books can be borrowed for a period of 15 days.",
    "admission_611": "For admissions, visit our official portal.",
    "fees_612": "B.Tech fees: ₹2,00,000 per year.",
    "library_613": "Library is open from 8 AM to 8 PM.",
    "fees_614": "M.Tech fees: ₹1,80,000 per year.",
    "library_615": "Books can be borrowed for a period of 15 days.",
    "placement_616": "Our highest package last year was ₹45 LPA.",
    "admission_617": "For admissions, visit our official portal.",
    "courses_618": "Our courses include engineering, management, science, and humanities.",
    "events_619": "We host cultural and technical events throughout the year.",
    "courses_620": "Visit sathyabama.ac.in/courses for the complete list.",
    "courses_621": "Our courses include engineering, management, science, and humanities.",
    "library_622": "You can access e-resources using your student login.",
    "fees_623": "B.Tech fees: ₹2,00,000 per year.",
    "courses_624": "Our courses include engineering, management, science, and humanities.",
    "greeting_625": "Hello! How can I help you today?",
    "library_626": "Library is open from 8 AM to 8 PM.",
    "fees_627": "MBA fees: ₹2,50,000 per year.",
    "placement_628": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_629": "You can access e-resources using your student login.",
    "placement_630": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_631": "You can access e-resources using your student login.",
    "placement_632": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_633": "Library is open from 8 AM to 8 PM.",
    "placement_634": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "hostel_635": "Hostel fees depend on the type of accommodation.",
    "courses_636": "Our courses include engineering, management, science, and humanities.",
    "admission_637": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_638": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_639": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "fees_640": "PhD fees vary depending on the department.",
    "events_641": "We host cultural and technical events throughout the year.",
    "events_642": "We host cultural and technical events throughout the year.",
    "events_643": "Sathyabama Fest is our annual cultural festival.",
    "library_644": "Books can be borrowed for a period of 15 days.",
    "courses_645": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_646": "Sathyabama Fest is our annual cultural festival.",
    "greeting_647": "Hi there! What can I do for you?",
    "courses_648": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_649": "Separate hostels for boys and girls are available.",
    "library_650": "You can access e-resources using your student login.",
    "courses_651": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "courses_652": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_653": "Library is open from 8 AM to 8 PM.",
    "library_654": "You can access e-resources using your student login.",
    "placement_655": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "courses_656": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_657": "M.Tech fees: ₹1,80,000 per year.",
    "library_658": "Library is open from 8 AM to 8 PM.",
    "courses_659": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_660": "PhD fees vary depending on the department.",
    "placement_661": "Our highest package last year was ₹45 LPA.",
    "courses_662": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_663": "Books can be borrowed for a period of 15 days.",
    "placement_664": "Our highest package last year was ₹45 LPA.",
    "library_665": "Library is open from 8 AM to 8 PM.",
    "fees_666": "MBA fees: ₹2,50,000 per year.",
    "hostel_667": "Separate hostels for boys and girls are available.",
    "library_668": "Library is open from 8 AM to 8 PM.",
    "library_669": "You can access e-resources using your student login.",
    "library_670": "Library is open from 8 AM to 8 PM.",
    "placement_671": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "admission_672": "You can apply online at sathyabama.ac.in/admissions.",
    "library_673": "You can access e-resources using your student login.",
    "greeting_674": "Hello! How can I help you today?",
    "hostel_675": "Separate hostels for boys and girls are available.",
    "fees_676": "M.Tech fees: ₹1,80,000 per year.",
    "placement_677": "We have a placement record of over 90%.",
    "library_678": "Books can be borrowed for a period of 15 days.",
    "courses_679": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_680": "MBA fees: ₹2,50,000 per year.",
    "courses_681": "Visit sathyabama.ac.in/courses for the complete list.",
    "greeting_682": "Greetings! How may I assist you?",
    "admission_683": "For admissions, visit our official portal.",
    "events_684": "We host cultural and technical events throughout the year.",
    "fees_685": "M.Tech fees: ₹1,80,000 per year.",
    "events_686": "Sathyabama Fest is our annual cultural festival.",
    "greeting_687": "Hello! How can I help you today?",
    "hostel_688": "Separate hostels for boys and girls are available.",
    "fees_689": "MBA fees: ₹2,50,000 per year.",
    "admission_690": "You can apply online at sathyabama.ac.in/admissions.",
    "courses_691": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "hostel_692": "Separate hostels for boys and girls are available.",
    "greeting_693": "Greetings! How may I assist you?",
    "fees_694": "B.Tech fees: ₹2,00,000 per year.",
    "placement_695": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "fees_696": "B.Tech fees: ₹2,00,000 per year.",
    "greeting_697": "Greetings! How may I assist you?",
    "events_698": "Hackathons and workshops are conducted regularly.",
    "admission_699": "For admissions, visit our official portal.",
    "admission_700": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_701": "B.Tech fees: ₹2,00,000 per year.",
    "greeting_702": "Hi there! What can I do for you?",
    "fees_703": "M.Tech fees: ₹1,80,000 per year.",
    "library_704": "Books can be borrowed for a period of 15 days.",
    "events_705": "Hackathons and workshops are conducted regularly.",
    "fees_706": "PhD fees vary depending on the department.",
    "courses_707": "Visit sathyabama.ac.in/courses for the complete list.",
    "placement_708": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "courses_709": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_710": "You can access e-resources using your student login.",
    "greeting_711": "Greetings! How may I assist you?",
    "admission_712": "You can apply online at sathyabama.ac.in/admissions.",
    "greeting_713": "Hi there! What can I do for you?",
    "hostel_714": "Separate hostels for boys and girls are available.",
    "library_715": "You can access e-resources using your student login.",
    "placement_716": "We have a placement record of over 90%.",
    "greeting_717": "Greetings! How may I assist you?",
    "hostel_718": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_719": "Visit sathyabama.ac.in/courses for the complete list.",
    "placement_720": "We have a placement record of over 90%.",
    "admission_721": "For admissions, visit our official portal.",
    "greeting_722": "Hi there! What can I do for you?",
    "courses_723": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "library_724": "Library is open from 8 AM to 8 PM.",
    "courses_725": "Our courses include engineering, management, science, and humanities.",
    "courses_726": "Visit sathyabama.ac.in/courses for the complete list.",
    "greeting_727": "Hello! How can I help you today?",
    "admission_728": "For admissions, visit our official portal.",
    "greeting_729": "Greetings! How may I assist you?",
    "library_730": "Library is open from 8 AM to 8 PM.",
    "hostel_731": "Separate hostels for boys and girls are available.",
    "library_732": "You can access e-resources using your student login.",
    "admission_733": "Admission details are available on our website.",
    "hostel_734": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "events_735": "We host cultural and technical events throughout the year.",
    "hostel_736": "Separate hostels for boys and girls are available.",
    "hostel_737": "Hostel fees depend on the type of accommodation.",
    "courses_738": "Our courses include engineering, management, science, and humanities.",
    "placement_739": "Our highest package last year was ₹45 LPA.",
    "library_740": "Books can be borrowed for a period of 15 days.",
    "placement_741": "Our highest package last year was ₹45 LPA.",
    "fees_742": "M.Tech fees: ₹1,80,000 per year.",
    "events_743": "We host cultural and technical events throughout the year.",
    "library_744": "Books can be borrowed for a period of 15 days.",
    "events_745": "We host cultural and technical events throughout the year.",
    "greeting_746": "Hi there! What can I do for you?",
    "library_747": "Books can be borrowed for a period of 15 days.",
    "admission_748": "For admissions, visit our official portal.",
    "greeting_749": "Greetings! How may I assist you?",
    "admission_750": "For admissions, visit our official portal.",
    "hostel_751": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "courses_752": "Visit sathyabama.ac.in/courses for the complete list.",
    "events_753": "Sathyabama Fest is our annual cultural festival.",
    "events_754": "Hackathons and workshops are conducted regularly.",
    "greeting_755": "Hello! How can I help you today?",
    "events_756": "We host cultural and technical events throughout the year.",
    "admission_757": "For admissions, visit our official portal.",
    "greeting_758": "Hi there! What can I do for you?",
    "greeting_759": "Greetings! How may I assist you?",
    "placement_760": "Our highest package last year was ₹45 LPA.",
    "library_761": "You can access e-resources using your student login.",
    "admission_762": "You can apply online at sathyabama.ac.in/admissions.",
    "hostel_763": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_764": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_765": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_766": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "greeting_767": "Hi there! What can I do for you?",
    "events_768": "Hackathons and workshops are conducted regularly.",
    "fees_769": "M.Tech fees: ₹1,80,000 per year.",
    "placement_770": "Our highest package last year was ₹45 LPA.",
    "admission_771": "You can apply online at sathyabama.ac.in/admissions.",
    "greeting_772": "Hello! How can I help you today?",
    "courses_773": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_774": "Admission details are available on our website.",
    "library_775": "You can access e-resources using your student login.",
    "library_776": "Library is open from 8 AM to 8 PM.",
    "events_777": "We host cultural and technical events throughout the year.",
    "library_778": "Library is open from 8 AM to 8 PM.",
    "placement_779": "Our highest package last year was ₹45 LPA.",
    "hostel_780": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "library_781": "Books can be borrowed for a period of 15 days.",
    "library_782": "Library is open from 8 AM to 8 PM.",
    "courses_783": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_784": "Hostel fees depend on the type of accommodation.",
    "courses_785": "Our courses include engineering, management, science, and humanities.",
    "fees_786": "B.Tech fees: ₹2,00,000 per year.",
    "events_787": "Hackathons and workshops are conducted regularly.",
    "admission_788": "For admissions, visit our official portal.",
    "events_789": "Sathyabama Fest is our annual cultural festival.",
    "greeting_790": "Greetings! How may I assist you?",
    "greeting_791": "Greetings! How may I assist you?",
    "fees_792": "M.Tech fees: ₹1,80,000 per year.",
    "events_793": "Hackathons and workshops are conducted regularly.",
    "admission_794": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_795": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "admission_796": "You can apply online at sathyabama.ac.in/admissions.",
    "greeting_797": "Hello! How can I help you today?",
    "admission_798": "You can apply online at sathyabama.ac.in/admissions.",
    "admission_799": "You can apply online at sathyabama.ac.in/admissions.",
    "placement_800": "Our highest package last year was ₹45 LPA.",
    "admission_801": "Admission details are available on our website.",
    "library_802": "Books can be borrowed for a period of 15 days.",
    "admission_803": "You can apply online at sathyabama.ac.in/admissions.",
    "admission_804": "Admission details are available on our website.",
    "fees_805": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_806": "Hostel fees depend on the type of accommodation.",
    "admission_807": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_808": "B.Tech fees: ₹2,00,000 per year.",
    "greeting_809": "Hi there! What can I do for you?",
    "admission_810": "Admission details are available on our website.",
    "library_811": "Books can be borrowed for a period of 15 days.",
    "library_812": "You can access e-resources using your student login.",
    "placement_813": "We have a placement record of over 90%.",
    "events_814": "Sathyabama Fest is our annual cultural festival.",
    "placement_815": "Our highest package last year was ₹45 LPA.",
    "placement_816": "We have a placement record of over 90%.",
    "admission_817": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_818": "MBA fees: ₹2,50,000 per year.",
    "fees_819": "PhD fees vary depending on the department.",
    "placement_820": "Our highest package last year was ₹45 LPA.",
    "courses_821": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "hostel_822": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "library_823": "You can access e-resources using your student login.",
    "events_824": "Sathyabama Fest is our annual cultural festival.",
    "hostel_825": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_826": "Our highest package last year was ₹45 LPA.",
    "courses_827": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_828": "Sathyabama Fest is our annual cultural festival.",
    "events_829": "We host cultural and technical events throughout the year.",
    "hostel_830": "Separate hostels for boys and girls are available.",
    "library_831": "You can access e-resources using your student login.",
    "courses_832": "Our courses include engineering, management, science, and humanities.",
    "admission_833": "Admission details are available on our website.",
    "fees_834": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_835": "Separate hostels for boys and girls are available.",
    "events_836": "We host cultural and technical events throughout the year.",
    "courses_837": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_838": "Our highest package last year was ₹45 LPA.",
    "fees_839": "MBA fees: ₹2,50,000 per year.",
    "admission_840": "You can apply online at sathyabama.ac.in/admissions.",
    "fees_841": "MBA fees: ₹2,50,000 per year.",
    "admission_842": "For admissions, visit our official portal.",
    "placement_843": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "events_844": "We host cultural and technical events throughout the year.",
    "fees_845": "MBA fees: ₹2,50,000 per year.",
    "admission_846": "Admission details are available on our website.",
    "library_847": "You can access e-resources using your student login.",
    "library_848": "You can access e-resources using your student login.",
    "greeting_849": "Greetings! How may I assist you?",
    "admission_850": "Admission details are available on our website.",
    "hostel_851": "Separate hostels for boys and girls are available.",
    "events_852": "Hackathons and workshops are conducted regularly.",
    "fees_853": "M.Tech fees: ₹1,80,000 per year.",
    "events_854": "Hackathons and workshops are conducted regularly.",
    "courses_855": "Our courses include engineering, management, science, and humanities.",
    "hostel_856": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_857": "MBA fees: ₹2,50,000 per year.",
    "hostel_858": "Hostel fees depend on the type of accommodation.",
    "greeting_859": "Hi there! What can I do for you?",
    "placement_860": "Our highest package last year was ₹45 LPA.",
    "events_861": "Hackathons and workshops are conducted regularly.",
    "fees_862": "B.Tech fees: ₹2,00,000 per year.",
    "library_863": "Books can be borrowed for a period of 15 days.",
    "admission_864": "For admissions, visit our official portal.",
    "admission_865": "You can apply online at sathyabama.ac.in/admissions.",
    "events_866": "We host cultural and technical events throughout the year.",
    "fees_867": "M.Tech fees: ₹1,80,000 per year.",
    "placement_868": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "hostel_869": "Separate hostels for boys and girls are available.",
    "library_870": "You can access e-resources using your student login.",
    "courses_871": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_872": "You can apply online at sathyabama.ac.in/admissions.",
    "events_873": "We host cultural and technical events throughout the year.",
    "events_874": "We host cultural and technical events throughout the year.",
    "placement_875": "We have a placement record of over 90%.",
    "fees_876": "PhD fees vary depending on the department.",
    "events_877": "Hackathons and workshops are conducted regularly.",
    "library_878": "You can access e-resources using your student login.",
    "courses_879": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "greeting_880": "Greetings! How may I assist you?",
    "events_881": "We host cultural and technical events throughout the year.",
    "greeting_882": "Hi there! What can I do for you?",
    "hostel_883": "Separate hostels for boys and girls are available.",
    "hostel_884": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_885": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_886": "Our highest package last year was ₹45 LPA.",
    "library_887": "Library is open from 8 AM to 8 PM.",
    "library_888": "You can access e-resources using your student login.",
    "events_889": "Sathyabama Fest is our annual cultural festival.",
    "placement_890": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "placement_891": "We have a placement record of over 90%.",
    "placement_892": "Our highest package last year was ₹45 LPA.",
    "library_893": "Library is open from 8 AM to 8 PM.",
    "courses_894": "Visit sathyabama.ac.in/courses for the complete list.",
    "hostel_895": "Hostel fees depend on the type of accommodation.",
    "greeting_896": "Hello! How can I help you today?",
    "courses_897": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_898": "B.Tech fees: ₹2,00,000 per year.",
    "fees_899": "MBA fees: ₹2,50,000 per year.",
    "hostel_900": "Separate hostels for boys and girls are available.",
    "library_901": "Books can be borrowed for a period of 15 days.",
    "greeting_902": "Hi there! What can I do for you?",
    "fees_903": "PhD fees vary depending on the department.",
    "hostel_904": "Separate hostels for boys and girls are available.",
    "events_905": "Hackathons and workshops are conducted regularly.",
    "library_906": "Library is open from 8 AM to 8 PM.",
    "fees_907": "PhD fees vary depending on the department.",
    "placement_908": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "greeting_909": "Greetings! How may I assist you?",
    "courses_910": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "courses_911": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "courses_912": "Visit sathyabama.ac.in/courses for the complete list.",
    "library_913": "Library is open from 8 AM to 8 PM.",
    "courses_914": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "placement_915": "Our highest package last year was ₹45 LPA.",
    "hostel_916": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "hostel_917": "Hostel fees depend on the type of accommodation.",
    "library_918": "You can access e-resources using your student login.",
    "admission_919": "You can apply online at sathyabama.ac.in/admissions.",
    "events_920": "We host cultural and technical events throughout the year.",
    "fees_921": "M.Tech fees: ₹1,80,000 per year.",
    "library_922": "Library is open from 8 AM to 8 PM.",
    "events_923": "Hackathons and workshops are conducted regularly.",
    "events_924": "We host cultural and technical events throughout the year.",
    "fees_925": "M.Tech fees: ₹1,80,000 per year.",
    "greeting_926": "Hi there! What can I do for you?",
    "greeting_927": "Hi there! What can I do for you?",
    "courses_928": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "events_929": "We host cultural and technical events throughout the year.",
    "placement_930": "We have a placement record of over 90%.",
    "hostel_931": "Hostel fees depend on the type of accommodation.",
    "hostel_932": "Hostel fees depend on the type of accommodation.",
    "events_933": "Sathyabama Fest is our annual cultural festival.",
    "library_934": "Library is open from 8 AM to 8 PM.",
    "library_935": "Library is open from 8 AM to 8 PM.",
    "library_936": "You can access e-resources using your student login.",
    "hostel_937": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "fees_938": "PhD fees vary depending on the department.",
    "events_939": "Sathyabama Fest is our annual cultural festival.",
    "admission_940": "For admissions, visit our official portal.",
    "greeting_941": "Hi there! What can I do for you?",
    "fees_942": "B.Tech fees: ₹2,00,000 per year.",
    "events_943": "We host cultural and technical events throughout the year.",
    "hostel_944": "Hostels have Wi-Fi, mess, and recreational facilities.",
    "placement_945": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "greeting_946": "Hello! How can I help you today?",
    "placement_947": "Our highest package last year was ₹45 LPA.",
    "courses_948": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "fees_949": "B.Tech fees: ₹2,00,000 per year.",
    "placement_950": "We have a placement record of over 90%.",
    "greeting_951": "Hi there! What can I do for you?",
    "greeting_952": "Hello! How can I help you today?",
    "hostel_953": "Separate hostels for boys and girls are available.",
    "events_954": "Hackathons and workshops are conducted regularly.",
    "admission_955": "You can apply online at sathyabama.ac.in/admissions.",
    "hostel_956": "Hostel fees depend on the type of accommodation.",
    "admission_957": "Admission details are available on our website.",
    "library_958": "Library is open from 8 AM to 8 PM.",
    "admission_959": "Admission details are available on our website.",
    "placement_960": "We have a placement record of over 90%.",
    "placement_961": "Our highest package last year was ₹45 LPA.",
    "library_962": "You can access e-resources using your student login.",
    "events_963": "Hackathons and workshops are conducted regularly.",
    "placement_964": "We have a placement record of over 90%.",
    "admission_965": "Admission details are available on our website.",
    "placement_966": "Top recruiters include TCS, Infosys, Wipro, and Amazon.",
    "library_967": "You can access e-resources using your student login.",
    "greeting_968": "Hello! How can I help you today?",
    "greeting_969": "Hi there! What can I do for you?",
    "events_970": "We host cultural and technical events throughout the year.",
    "events_971": "Hackathons and workshops are conducted regularly.",
    "fees_972": "M.Tech fees: ₹1,80,000 per year.",
    "hostel_973": "Separate hostels for boys and girls are available.",
    "greeting_974": "Hello! How can I help you today?",
    "admission_975": "For admissions, visit our official portal.",
    "admission_976": "For admissions, visit our official portal.",
    "library_977": "Books can be borrowed for a period of 15 days.",
    "courses_978": "Visit sathyabama.ac.in/courses for the complete list.",
    "fees_979": "PhD fees vary depending on the department.",
    "hostel_980": "Separate hostels for boys and girls are available.",
    "courses_981": "We offer B.Tech, MBA, M.Tech, BSc, MSc, PhD, and more.",
    "admission_982": "You can apply online at sathyabama.ac.in/admissions.",
    "admission_983": "Admission details are available on our website.",
    "greeting_984": "Hi there! What can I do for you?",
    "hostel_985": "Separate hostels for boys and girls are available.",
    "courses_986": "Visit sathyabama.ac.in/courses for the complete list.",
    "events_987": "Hackathons and workshops are conducted regularly.",
    "courses_988": "Our courses include engineering, management, science, and humanities.",
    "library_989": "Library is open from 8 AM to 8 PM.",
    "events_990": "Hackathons and workshops are conducted regularly.",
    "library_991": "You can access e-resources using your student login.",
    "library_992": "Books can be borrowed for a period of 15 days.",
    "placement_993": "Our highest package last year was ₹45 LPA.",
    "events_994": "Hackathons and workshops are conducted regularly.",
    "fees_995": "PhD fees vary depending on the department.",
    "events_996": "We host cultural and technical events throughout the year.",
    "library_997": "You can access e-resources using your student login.",
    "greeting_998": "Greetings! How may I assist you?",
    "fees_999": "MBA fees: ₹2,50,000 per year."
}

# ==============================
# FUNCTIONS
# ==============================
def log_conversation(user_input, bot_response):
    """Log every conversation to a file."""
    log_entry = {
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "user": user_input,
        "bot": bot_response
    }

    if not os.path.exists(LOG_FILE):
        with open(LOG_FILE, "w") as f:
            json.dump([], f, indent=4)

    with open(LOG_FILE, "r+") as f:
        data = json.load(f)
        data.append(log_entry)
        f.seek(0)
        json.dump(data, f, indent=4)


def get_gemini_response(user_input):
    """Ask Gemini with full chat history for context memory."""
    global chat_history
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")

        # add user input to history
        chat_history.append({"role": "user", "parts": [user_input]})

        # generate with full conversation
        response = model.generate_content(chat_history)

        bot_reply = response.text.strip() if response and response.text else "I couldn’t generate a response."

        # add bot reply to history
        chat_history.append({"role": "model", "parts": [bot_reply]})

        return bot_reply

    except Exception as e:
        return f"⚠️ Error fetching Gemini response: {str(e)}"


def generate_response(user_input):
    """Main response generator."""
    lower_input = user_input.lower()

    # Special: Time/Date
    if "time" in lower_input:
        return f"⏰ The current time is {datetime.datetime.now().strftime('%H:%M:%S')}."
    if "date" in lower_input:
        return f"📅 Today's date is {datetime.datetime.now().strftime('%Y-%m-%d')}."

    # Check static dictionary
    for key in faq_data:
        if key in lower_input:
            return faq_data[key]

    # Gemini fallback
    return get_gemini_response(user_input)


# ==============================
# MAIN CHAT LOOP
# ==============================
if __name__ == "__main__":
    print("🤖 Sathyabama University Chatbot (type 'exit' to quit)\n")

    while True:
        user_inp = input("You: ").strip()
        if user_inp.lower() in ["exit", "quit"]:
            print("Bot: Goodbye! 👋")
            break

        bot_out = generate_response(user_inp)
        print("Bot:", bot_out)

        # Log conversation
        log_conversation(user_inp, bot_out)
